### ISSUE TITLE
Potential error due to the unreleased lock 

### ISSUE THREAD

**Issue by anson-lo** [Seagate/cortx-s3server#1037]
Dear developers:
         Thank you for your checking. In the method `mempool_destroy`, the lock `&pool->lock` may be not released if the branch condition satisfies and the method returns.
       
https://github.com/Seagate/cortx-s3server/blob/d684426013aecda8b21d59e2fcc09073730f3fd2/mempool/s3_memory_pool.c#L539
https://github.com/Seagate/cortx-s3server/blob/d684426013aecda8b21d59e2fcc09073730f3fd2/mempool/s3_memory_pool.c#L543

```
int mempool_destroy(MemoryPoolHandle *handle) {
  struct mempool *pool = NULL;
  struct memory_pool_element *pool_item;
  char *log_msg_fmt = "mempool(%p): free(%p) called for buffer size(%zu)";
  char log_msg[200];

  if (handle == NULL) {
    return S3_MEMPOOL_INVALID_ARG;
  }

  pool = (struct mempool *)*handle;
  if (pool == NULL) {
    return S3_MEMPOOL_INVALID_ARG;
  }

  if ((pool->flags & ENABLE_LOCKING) != 0) {
    pthread_mutex_lock(&pool->lock); // the lock
  }

  if (*handle == NULL) {
    return S3_MEMPOOL_INVALID_ARG;  //return without releasing
  }

  ...;
}
```

Best,

**Comment by johnbent** [comment]
Thanks @anson-lo !  Just curious: how did you find this by the way?  Just reading the code or you did some automated analysis?

**Comment by nileshgovande** [comment]
Thanks @anson-lo .  You're right, this looks like a bug.  Would you like to submit the patch yourself?  Let us know and that'd be awesome.  Otherwise, we can fix it.  Thanks for catching this and reporting

**Comment by anson-lo** [comment]
@johnbent It is reported by a static code scanner.
@nileshgovande I am happy to pull a request. Would be done soon.

**Comment by nileshgovande** [comment]
Thanks, @anson-lo Which static code scanner?

**Comment by mukul-seagate11** [comment]
> Thanks, @anson-lo Which static code scanner?

Nilesh, Its reported in Codacy

**Comment by anson-lo** [comment]
@nileshgovande We use [Pinpoint,](https://qingkaishi.github.io/public_pdfs/PLDI2018.pdf) a static analysis tool similar to Codacy.

**Comment by nileshgovande** [comment]
No @mukul-seagate11 - its not
CC @johnbent 

We will  check on Pinpoint @anson-lo

**Comment by nileshgovande** [comment]
PR - https://github.com/Seagate/cortx-s3server/pull/1041

**Comment by nileshgovande** [comment]
Changes merged to main

**Comment by swanand-gadre** [comment]
Thanks @johnbent for looping me in.

Similar condition is described as a weakness here -> https://cwe.mitre.org/data/definitions/401.html

Since memory lock is not released in specific condition, It leads to not sufficiently tracking and releasing allocated memory after it has been used, which slowly consumes remaining memory.

It impacts availability (reduced performance, article also mention, potential DoS attack).

Hi @nileshgovande 

I see that the specific condition is now fixed with pool->lock released with pthread_mutex_unlock(&pool->lock);
Also code to reset *handle and free items in the free list does clean-up.

However do we need to also add a similar code, in 

if (handle == NULL) {
    return S3_MEMPOOL_INVALID_ARG;
}

Or will it not have pool-lock if handle is NULL ?

Regards
Swanand

**Comment by anson-lo** [comment]
Could we apply CVE ID for this issue? (Similar to CVE-2014-3657, CVE-2015-8340,CVE-2020-12771). Thanks so much.

**Comment by johnbent** [comment]
Hey @swanand-gadre , do you have an answer for @anson-lo ?

**Comment by swanand-gadre** [comment]
Hi @anson-lo 

Thank you for your interest,

Is there any POC or end user scenario available, where this condition is hit and shows evidence of impact?

**Comment by swanand-gadre** [comment]
Hi @anson-lo 

Does the same fix applies to 

if (handle == NULL) {
return S3_MEMPOOL_INVALID_ARG;
}

Do you want to try raising it with https://cve.mitre.org/cve/request_id.html

Regards
Swanand

**Comment by anson-lo** [comment]
@swanand-gadre Hi, it seems the individuals are more difficult to request this without assistance from developers. I tried before but got no reply. Could you please raise it?

**Comment by swanand-gadre** [comment]
Hi @anson-lo 

In my opinion, since your tool uncovered it, it is appropriate you raise request for CVE ID.
Typically, committee would reach out to the products, in case of doubts/queries.

However requesting you to take initial step.

Also I wanted to know your feedback, if , the same fix applies to?

if (handle == NULL) {
return S3_MEMPOOL_INVALID_ARG;
}

Regards
Swanand

**Comment by anson-lo** [comment]
@swanand-gadre Thanks, I would take an initial step.

https://github.com/Seagate/cortx-s3server/blob/d684426013aecda8b21d59e2fcc09073730f3fd2/mempool/s3_memory_pool.c#L529-L540

From my view, applying to `handle==NULL` is not necessary, since the lock `pool->lock` is acquired later.

**Comment by swanand-gadre** [comment]
Hi @anson-lo 

Any further updates ?

Regards
Swanand

**Comment by anson-lo** [comment]
@swanand-gadre Hi, I have submitted my CVE application form but haven't received any notifications so far.

**Comment by johnbent** [comment]
@anson-lo , by the way, this has been fixed now in the code. So should we still file for the CVE?

**Comment by anson-lo** [comment]
OK, thanks for your time and help
