### ISSUE TITLE
Migrate auth/server to JDK 8

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-s3server#1592]
Hi, 

While I read through the build file (pom.xml), I noticed that the code is compile with JDK 1.7.

![image](https://user-images.githubusercontent.com/77140436/140257327-37e4fb16-9951-4a9b-973f-ea9e8f47fb15.png)

Should we upgrade to JDK 8 instead ? This is because JDK 1.7 had end of supported, see [here](https://en.wikipedia.org/wiki/Java_version_history) 

We could use any open JDK 8 except Oracle since Oracle JDK no longer free.

**Comment by hessio** [comment]
I am just checking with @sachitanands for help with this question as I am not sure what the reason for this is.

**Comment by kiwionly2** [comment]
@hessio 

The latest Java patches contain important enhancements to improve performance, stability and security of the Java applications. 

Because JDK 1.7 is no longer publicly supported ( except the paid support by Oracle ),  it is always good to upgrade latest version for the reason above.

**Comment by hessio** [comment]
Yes I agree with you it makes sense to be on the latest version. There must be some dependencies or other reason that we have not upgraded to this latest version but I am not sure what this reason is. @nileshgovande can you provide some insight here?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26088. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by kiwionly2** [comment]
Just add an example here like why latest version will be better.

Here the recent [vulnerability](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228 ) ( explanation [here ](https://blog.cloudflare.com/secure-how-your-servers-connect-to-the-internet-today/)) which cause by Apache Log4j2 <=2.14.1. ( PR #1654 to #1660 had created by github Dependabot security updates to fix this issue. )

By upgrade to Java 8, as explain in the link above, we could get better securities.

> Java 8u121 (see https://www.oracle.com/java/technologies/javase/8u121-relnotes.html) protects against remote code execution by defaulting "com.sun.jndi.rmi.object.trustURLCodebase" and "com.sun.jndi.cosnaming.object.trustURLCodebase" to "false".

**Comment by hessio** [comment]
Currently we are in the process of replacing the cortx-s3server with RGW, so this will be retired then, that is why we will not be upgrading the code in this repo. But this was a good find it is unfortunate that this repo is being retired but it is good that we have cortx-rgw because this is really cool. As a result I will close this issue.

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed

**Comment by cortx-admin** [comment]
> Patrick Hession commented in Jira Server:

Issue closed
