### ISSUE TITLE
README has links to 'dev' branch

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-s3server#337]
@Saumya-Sunder and @nileshgovande ,

I wanted to do a bit of work adding some documentation to help the community understand our S3 repo a bit better but I got confused by something.  The default branch is 'main' but the README has links explicitly to files in the 'dev' branch.  It would be much better if the links are relative links pointing to files in the same branch.

Can this be fixed please?  What is the explanation for this?  Was this done intentionally?

**Comment by nileshgovande** [comment]
@johnbent 

Its not all the links but only a couple of links missed out in the below text - definitely not intentional

**_Refer to the CORTX-S3 Server Quickstart Guide to build and test the CORTX-S3 Server.

Contribute to CORTX-S3 Server
We welcome all Source Code and Documentation contributions to the CORTX-S3 Server component repository. Refer to the CORTX-S3 Server Contributing Guide document to submit your contributions._**

@Saumya-Sunder - Pls fix

**Comment by nileshgovande** [comment]
Merged
