### ISSUE TITLE
Complete Quick Start Guide

### ISSUE THREAD

**Issue by harrison-seow-seagate** [Seagate/cortx-s3server#595]
[S3 Server Quick Start Guide](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md) is incomplete.
I started working on S3 Server some time ago so I knew which ISO / Base OS to use as the VM base image. I was browsing through the issue and saw that the Local VM Setup guide link has been removed. Steps to install kernel devel for the image is also missing based on the tests (also mentioned in [Issue 217](https://github.com/Seagate/cortx-motr/issues/217)).

Not sure if this is linked to [Issue 257](https://github.com/Seagate/cortx/issues/257).

**Comment by Saumya-Sunder** [comment]
Hey @harrison-seow-seagate, thanks for creating this issue, I faced the same as well. This issue is kind of linked to Issue 257 as we need to write the whole process of setting up a Local VM and then add the Kernel details in the article. However, this is an old version and we need to update it. I will follow up with the component team on this and update the documentation accordingly. Will keep you posted :)

**Comment by johnbent** [comment]
@hessio, did you just get this QSG working?  If so, how did you avoid the problem that @harrison-seow-seagate is seeing?

**Comment by hessio** [comment]
Unfortunately, I have not worked on setting that up yet @johnbent

**Comment by nileshgovande** [comment]
Stale issue - closing
