### ISSUE TITLE
Hello world example for S3 REST api

### ISSUE THREAD

**Issue by kiwionly** [Seagate/cortx-s3server#604]
hi, 

Is that a "hello world" sample for S3 REST api for CORTX so I have something to play around with ?

I have installed CORTX on VMware workstation and try to understand how the thing work.

**Comment by Saumya-Sunder** [comment]
Hey @kiwionly, at this moment no. But I would love to document it, what exactly are you trying to accomplish? If you want to test S3, you surely can using the steps here:
- https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#13-Code-Compilation-and-Unit-Test . 
- https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#14-Test-your-Build-using-S3-CLI
- https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md#15-Test-a-Specific-MOTR-Version-using-CORX-S3-Server

@nileshgovande please assign someone so that I could document a hello world example for S3?

**Comment by kiwionly** [comment]
I was thinking it as a way of introduction to CORTX, so far I only running the sanity test ( I guess using CLI), but it look kind like a black box to me.

If there is a "hello world" that showing operation like PUT and GET using CURL ( or HTTP protocol equivalent) after install cortx-s3 server, it will be much easier to understand for most web developer.

**Comment by Saumya-Sunder** [comment]
Sure @kiwionly. I will add the link to the command once I document it.

**Comment by nileshgovande** [comment]
@kiwionly - we do not have anything in curl but you can definitely refer aws documentation at https://docs.aws.amazon.com/AmazonS3/latest/API/s3-api.pdf 
cortx supports the same.
One more way is to run aws commands, do a wireshark trace (or tcpdump) and study the pcap file using wireshark.

**Comment by kiwionly** [comment]
ok, i will look into the document.
